### ISSUE TITLE
CATALOG: problem on Css

### ISSUE THREAD

**Issue by mconte79** [geosolutions-it/geonode-mapstore-client#100]
Hi 
  I have custom dimension of geonode navbar. When I create a new map and try to add a layer the Catalog div go partially under navbar div so I cannot close it.
The div haven't an ID so i cannot insert a CSS style to resize it.
Best regards
Matteo

**Comment by giohappy** [comment]
Thanks for reporting your issue. We will keep in consideration.
Please consider that this client has not been released yet, thus no support is provided.
