### ISSUE TITLE
Client Mapstore-client in QgisServer

### ISSUE THREAD

**Issue by ideonion** [geosolutions-it/geonode-mapstore-client#102]
Hi good day.
Someone has tried the client mapstore2 in geonode 2.8 and using QgisServer. It's possible?
Thanks for your attention

**Comment by gioscarda** [comment]
Hi, no we did not but some of the advanced features of MS requires GeoServer in the back-end so support might be partial.

Notice that Qgis Web Client now uses MapStore as the base library hence supporting QGIS Server is totally possible with some work.
