### ISSUE TITLE
Error in google chrome smartphone browser

### ISSUE THREAD

**Issue by ideonion** [geosolutions-it/geonode-mapstore-client#103]
Hi good day

There is an error when viewing a layer or map with google chrome on smarphone.
What could be the problem?

![screenshot_2018-10-26-11-17-55-564_com android chrome](https://user-images.githubusercontent.com/43503132/47557847-fdc4ba80-d911-11e8-96d1-a04b5bc06d02.png)

**Comment by afabiani** [comment]
@ideonion hi, the mobile CSS have not implemented yet. Consider that there is no official release for this client yet. You will need to wait a bit more time for the mobile styling stuff.

**Comment by ideonion** [comment]
Thank you very much for your answer Afabiani

**Comment by kappu72** [comment]
Closed by https://github.com/geosolutions-it/geonode-mapstore-client/pull/113
