### ISSUE TITLE
Basic Structure and Themes

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/geonode-mapstore-client#11]
Optimize mapstore2 apis and imports into the DJango package.

Right now it is just importing the whole bundle (about 60Mbs) into the static folder. We should envisage a way to import only the needed classes.

Current mockup available [here](https://demo.geo-solutions.it/mockups/geonode-mapstore/index.html)

connected to #3 
connected to #43 
connected to #44 
connected to #45 
connected to #46 
connected to #47 
connected to #48 
connected to #49 
connected to #50

**Comment by gioscarda** [comment]
@tdipisa can we close this one? 

I see that all the children issues are now closed.
