### ISSUE TITLE
More Info in Identify doesn't work

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode-mapstore-client#120]
![2018-11-16 10_57_04-window](https://user-images.githubusercontent.com/19175505/48614449-9341f000-e98e-11e8-8e64-1f3cf3b148e0.png)

nominatim is requested via proxy,
it uses CORS in MapStore master

**Comment by gioscarda** [comment]
seems working now

I believe this is the consequence of the mapstore update in the geonode integration.
