### ISSUE TITLE
Missing error popup in style editor

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode-mapstore-client#125]
When style is not valid a popup icon should show in editor header.
It's probably missing because wrong parsing of response message.

**Comment by gioscarda** [comment]
There is a message (see the green arrow) into the editor header but it is not visible due its color:
![Selection_034.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb6105ee480a40012f1641f/125516c66e82c728ace21e0d46db9196268197a080e78013f709b2d86b56357c2301a03f32dfa17dbe1a7e020e5849a9480d0a17aff9892af4b43c70df0a0affcd7f1d2598694ef1e1c84afd13b0328a468fb7b98f4fc6e93521e6838d4a3f0c48.png)
No icons seem to be rendered.

**Comment by simboss** [comment]
"No icons seem to be rendered."

What do you mean?

**Comment by gioscarda** [comment]
I mean the popup icon (like the one in the picture below) mentioned by @allyoucanmap:
![Selection_035.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb6105ee480a40012f1641f/125516c66e82c728ace21e0d46db9196268197a080e78013f708b2d86b56357c2301a03f32dfa17dbe1a7e020e5849a9480d0a17aff9892af4b43c70df0a0affcd7f1d2598694ef1e1c84afd13b0328a488fb7b98f4fc6ef3a25e08b8f49360c48.png)
I've confirmed that it does not appear.
