### ISSUE TITLE
js error in layer preview when switching the styles

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/geonode-mapstore-client#147]
In the layer preview page (it should refer the `layer_detail.html` template) when switching the layer style an error occurs on the javascript side:
```
Uncaught TypeError: Cannot read property 'split' of undefined
    at HTMLInputElement.<anonymous> (geonode:tiger_roads:258)
    at HTMLInputElement.dispatch (assets.min.js?v=2.10rc4:4)
    at HTMLInputElement.q.handle (assets.min.js?v=2.10rc4:4)
```
So the style not changes.

**Comment by giohappy** [comment]
@afabiani this was an old issue that I thought it was fixed, wasn't it?

**Comment by afabiani** [comment]
Seems like a regression. On old instances (aka MapStand) it doesn't occur. In DEV it does (or at least it seems to be happening under certain circumstances)

**Comment by gioscarda** [comment]
This problem no longer occurs.
I will close this issue.
