### ISSUE TITLE
The "Create new style" popup does not appear in Safari

### ISSUE THREAD

**Issue by ppasq** [geosolutions-it/geonode-mapstore-client#149]
While clicking on the plus button "Add selected template to list of styles" the popup  does not appear in Safari. It works in Chrome for MacOS.

<img width="1686" alt="Screenshot 2019-04-10 at 12 10 12" src="https://user-images.githubusercontent.com/3024454/55870871-cb3e0f80-5b89-11e9-8d5a-9e8f2498c0c3.png">

**Comment by allyoucanmap** [comment]
connected to https://github.com/geosolutions-it/MapStore2/issues/3708
