### ISSUE TITLE
How to enable Search Location and Mouse Position?

### ISSUE THREAD

**Issue by lolob** [geosolutions-it/geonode-mapstore-client#150]
Hi,
I have successfully installed and run geonode-mapstore without much problems. Now I'm trying to have something similar to this example https://demo.geo-solutions.it/mockups/geonode-mapstore/edit_map.html#/ . Search Location and Mouse Position (footer) . First I study and look at these file; 

ms2_base_plugins.js  
ms2_composer_plugins.js  
ms2_map_embed_plugins.js  
ms2_map_viewer_plugins.js  
ms2_viewer_plugins.js 

I decided to update ms2_map_viewer_plugins.js as follows 
`{
                "name": "MousePosition",
                "cfg": {
                    "editCRS": true,
                    "showLabels": true,
                    "showToggle": true,
                    "filterAllowedCRS": [
                        "EPSG:4326",
                        "EPSG:3857"
                    ],
                    "additionalCRS": {}
                }
            },
{
                "name": "Search",
                "cfg": {
                    "withToggle": [
                        "max-width: 768px",
                        "min-width: 768px"
                    ]
                }
},`

Save and restart server. However, the Search and MousePosition not appear.

**Comment by afabiani** [comment]
You should also rebuild the client and run "collectstatic" on Django later on.

However, we just pushed a pre-relase 1.0rc0 on pypi which should already enable that plagin other than include several improvements from MapStore2 2019 01 release.

https://pypi.org/project/django-geonode-mapstore-client/1.0rc0/

**Comment by lolob** [comment]
Thank you @afabiani

**Comment by kerleven** [comment]
@lolob  I'm having the same issue, did you manage to get the plugins to work on the geonode-mapstore-client ?

**Comment by afabiani** [comment]
@lolob @kerleven I will send an update today.

**Comment by afabiani** [comment]
@lolob @kerleven could you please try

`pip install django-mapstore-adapter==1.0.0 --upgrade --no-cache`
`pip install django-geonode-mapstore-client==1.0rc2 --upgrade --no-cache`

run a `collectstatic` and restart the HTTPD service.

**Comment by lolob** [comment]
Yes.
I can confirm that it's working now.
Thank you for the efforts.
