### ISSUE TITLE
Some SLD are not saved correctly from MapStore Style Editor

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode-mapstore-client#151]
Some SLD are not saved correctly from MapStore Style Editor but the same style has been saved successfully from GeoServer admin UI.

**Comment by afabiani** [comment]
Ref to https://github.com/geosolutions-it/MapStand/issues/67#issuecomment-487486275

**Comment by allyoucanmap** [comment]
related to https://github.com/geosolutions-it/MapStore2/issues/3712

**Comment by allyoucanmap** [comment]
commit 3b646ae988641e2202d6f9fdd9fd3b7e2a8289fd

see PR in MapStore:
master https://github.com/geosolutions-it/MapStore2/pull/3718
branch 2019.01.01 https://github.com/geosolutions-it/MapStore2/pull/3724
