### ISSUE TITLE
Default style assignment only available inside style_edit page

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-mapstore-client#161]
The recently added button to assign default style to layer is only available inside the style_edit page (Editing Tools -> Edit style). while it's not available when the style is being edited from the layer view and the map view.

![image](https://user-images.githubusercontent.com/571129/57445411-97bad780-7252-11e9-85bf-c0e66bc2b4c8.png)

![image](https://user-images.githubusercontent.com/571129/57445425-9f7a7c00-7252-11e9-8f11-29ffb29aa5ff.png)

**Comment by simboss** [comment]
I think this is is very important.

It confuses me every time that I cannot make a style as the default.

**Comment by simboss** [comment]
@allyoucanmap is this work in mapstore or in geonode?

Can you tell us something?

**Comment by giohappy** [comment]
@simboss this is in GeoNode. 
I've assigned to @afabiani and @kappu72 since they are in charge of the fix.

**Comment by allyoucanmap** [comment]
@simboss @giohappy 
When I added this functionality to geonode-mapstore integration I only enabled it in the [layer_style_edit.html](https://github.com/geosolutions-it/geonode-mapstore-client/blob/master/geonode_mapstore_client/templates/geonode-mapstore-client/layer_style_edit.html#L43) template of this project.
We could solve this by enabling default style functionality in every templates that use Style Editor.

Note: probably it can be misleading to enable this functionality also in the map editing.

**Comment by simboss** [comment]
I would start by enabling this in the template we use when we inspect a layer.
I would not enable it in map editing.

@afabiani this is something you can do? I would not close this issue once you have done so we can do more testing. Just let us know when you do it.
