### ISSUE TITLE
Timeline shows on wrong layers

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geonode-mapstore-client#166]
I got this on dev.geonode.using [this](https://github.com/geosolutions-it/geonode-mapstore-client/files/3204999/ne_10m_populated_places_simple.zip) file, se gif below.
The layer is [this](https://dev.geonode.geo-solutions.it/layers/geonode:ne_10m_populated_places_simple0#/) one. This is critical to be fixed.
![gn](https://user-images.githubusercontent.com/693880/58138351-fb230d00-7c35-11e9-9ac3-3cf0c2d0efb8.gif)

**Comment by afabiani** [comment]
It seems like GeoServer 2.15.1 has some defects and cannot be used yet with a stable version of GeoNode.
Reverting back to GeoServer 2.14.2 seems to fix the issue.
Further testing to be done.

**Comment by simboss** [comment]
@afabiani we need more details to investigate and fix eventual issues.

Please, prepare a list for us to investigate.
Aside, 2.14.2 is already old, we should use 2.14.3 instead!

**Comment by afabiani** [comment]
Moved to https://github.com/GeoNode/geonode-mapstore-client/issues/7
