### ISSUE TITLE
Hard-coded URL paths and static url

### ISSUE THREAD

**Issue by GeoTob** [geosolutions-it/geonode-mapstore-client#169]
As part of my investigation here: https://github.com/GeoNode/geonode/issues/3738

Some of the variables used in html templates (e.g. `proxy` and `printUrl`) are hard-coded and don't update from Geonode's settings. Further, those variables are defined in multiple places making them hard to maintain.

Static URLs are generated using `{{ STATIC_URL }}` instead of the correct `{% static %}` tag, which leads to issues when serving static files from a different host (ie S3).

I have a working fork at https://github.com/GeoTob/geonode-mapstore-client/pull/1/files that attempts to fix those issues and I'm happy to make a PR against the upstream repo here. Note it doesn't yet fix all the issues, as the MS2 JavaScript also includes hard-coded URLs to `/static` and similar.

**Comment by afabiani** [comment]
@GeoTob PR are very welcomed. If you have resources to work on that I will be happy to review and test.
