### ISSUE TITLE
adding mapstore-client plugins 

### ISSUE THREAD

**Issue by kerleven** [geosolutions-it/geonode-mapstore-client#175]
Hi  I'm trying to add plugins such as add local vector files, and annotations to my mapstore client viewer. I try including the plugins code in the  **ms2_map_viewer_plugins.js** file and run collectstatic . but still nothing appears on the mapstore viewer. am I modifying the wrong file ?

( a similar issue was adressed in #150 )

**Comment by afabiani** [comment]
Moved to https://github.com/GeoNode/geonode-mapstore-client/issues/4
