### ISSUE TITLE
Style Editor Error

### ISSUE THREAD

**Issue by lolob** [geosolutions-it/geonode-mapstore-client#177]
Geonode 2.10rc4
Mapstore2 Client 1.3.1

![style_error](https://user-images.githubusercontent.com/15963902/60396373-7a7bf880-9b73-11e9-8979-faa1982357f2.png)

Meanwhile in Chrome developer console, it says these:

> 404 Not found http://192.168.11.246:9090/gs/geonode:fe_2007_02_county/style-check?access_token=0YJ9ywamKOL5u9r5kz8WLukh9AJ9xy ms2-geonode-api.js:15 

> 404 Not found http://192.168.11.246:9090/gs/geonode/fe_2007_02_county/ows?service=WMS&version=1.3.0&request=GetCapabilities&access_token=0YJ9ywamKOL5u9r5kz8WLukh9AJ9xy ms2-geonode-api.js:15

**Comment by afabiani** [comment]
Moved to https://github.com/GeoNode/geonode-mapstore-client/issues/3
