### ISSUE TITLE
Update MapStore to integrate fix to geometry editing

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-mapstore-client#202]
https://github.com/geosolutions-it/MapStore2/commit/fc87219e40b3872d87354a1d8677e65e68883f9b

**Comment by allyoucanmap** [comment]
@giohappy this commit has been included in the master of geonode-mapstore-client but currently I'm not able to test the original issue https://github.com/geosolutions-it/MapStore2/issues/6321 because the layer url and dowload links are broken

**Comment by giohappy** [comment]
I see it has bee closed, so let's close this too.
