### ISSUE TITLE
Identify problem in a GeoStory

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/geonode-mapstore-client#207]
@ElenaGallo commented on [Thu Feb 11 2021](https://github.com/geosolutions-it/support/issues/1142)

It is not possible to click on a feature of [this map](https://master.demo.geonode.org/maps/430) present in [this geostory](https://master.demo.geonode.org/apps/425/edit#/)

 **How to Reproduce**
- Login as user on master.demo
- Open [this geostory](https://master.demo.geonode.org/apps/425/edit#/) 
- Click a feature from the first map

*Current Result*
The Identify popup does not appears. From the [map](https://master.demo.geonode.org/maps/430), clicking on the feature, on conosle this error appears:

> GET https://googleads.g.doubleclick.net/pagead/id net::ERR_BLOCKED_BY_CLIENT

> GET https://static.doubleclick.net/instream/ad_status.js net::ERR_BLOCKED_BY_CLIENT

---

@allyoucanmap commented on [Thu Feb 11 2021](https://github.com/geosolutions-it/support/issues/1142#issuecomment-777412219)

@simboss @ElenaGallo there was an issue in MapStore with the identify component when multiple maps are used in the same app (geostorey, dashboard). The issue has been solved in a recent fix about the resolutions visibility limits https://github.com/geosolutions-it/MapStore2/pull/6407. I tried to update the submodule locally and the identify is working as expected.
To solve this issue we need to update the MapStore2 submodule and align the geonode-mapstore-client and it should take ~0.5dd but if it's not urgent I would suggest to wait the next PR about the layer embed where we could include the latest updates of MapStore2 master.

**Comment by giohappy** [comment]
@ElenaGallo from what I see this has been solved. Can we close this?

**Comment by allyoucanmap** [comment]
@giohappy It's solved on MapStore but the fix was merged two days ago on master so we need an additional update on the geonode-client

**Comment by giohappy** [comment]
I can see the popup correctly

![image](https://user-images.githubusercontent.com/571129/107747675-2017b780-6d18-11eb-99fe-c2ab15c1b4ac.png)

**Comment by giohappy** [comment]
ok, I see now that it works only for the first map. 
@allyoucanmap please upgrade again mapstore client.

**Comment by allyoucanmap** [comment]
@ElenaGallo @giohappy  master.demo has been updated, I  just a quick test and it seems to work, going to close this

**Comment by simboss** [comment]
@chpicone this is needed also for oaw!

we will need to upgrade them as well.

**Comment by chpicone** [comment]
@simboss thx.
