### ISSUE TITLE
Tile size problem problem for the layer on map 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/geonode-mapstore-client#214]
Changing the *WMS Layer tile size* from 256 to 512 from the Layer Settings panel and then saving the map, the *WMS Layer tile size* is not saved correctly

**How to Reproduce**
- Open [this map](https://master.demo.geonode.org/maps/479) 
- follow the steps of the video:

![www3](https://user-images.githubusercontent.com/56537133/109848163-3d251380-7c50-11eb-8142-9dc695d46ceb.gif)

*Expected result*
opening the saved map the *WMS Layer tile size* is 256 and not 512

**Comment by allyoucanmap** [comment]
fixed in this commit https://github.com/GeoNode/geonode-mapstore-client/commit/b78555f06794d29603ddc84cb851c85d814bc9ea and related to #211

**Comment by ElenaGallo** [comment]
@giohappy the test done, the issue is resolved
