### ISSUE TITLE
Redirect to the new client editor after metadata page update

### ISSUE THREAD

**Issue by marthamareal** [geosolutions-it/geonode-mapstore-client#240]
The client tags implemented in https://github.com/geosolutions-it/geonode/pull/862 can be used to set the correct back link inside the [metadata update redirection](https://github.com/geosolutions-it/geonode/blob/nexus_master/geonode/templates/metadata_form_js.html#L729)

**Comment by giohappy** [comment]
@marthamareal isn't this already fixed?

**Comment by marthamareal** [comment]
It was fixed @giohappy
