### ISSUE TITLE
Layer legend is not updated

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/geonode-mapstore-client#260]
By changing the style of the layer, the legend does not change accordingly

**How to Reproduce**
- See the steps in the gif below:

https://user-images.githubusercontent.com/56537133/181194652-85305f5c-22ef-4422-9fde-f5282df32ee8.mov

**Comment by giohappy** [comment]
closed in favour of https://github.com/GeoNode/geonode-mapstore-client/issues/1117
