### ISSUE TITLE
Update current map name on save

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode-mapstore-client#4]
Should we add the possibility to update the current map name on save? 
connected to #46
connected to #32

**Comment by gioscarda** [comment]
@allyoucanmap can we close this one?

I see that the connected issues are closed, so?

**Comment by gioscarda** [comment]
Currently in GeoNode you can update the map name only from the metadata editing page (you have also to fill all the mandatory fields to save that info).
@giohappy, should we consider this issue for the first release?

**Comment by giohappy** [comment]
@gioscarda  What's the effect of setting the name and the description here?

![image](https://user-images.githubusercontent.com/571129/54827775-0fd53a00-4cb3-11e9-83f1-67fec2a50aa5.png)

**Comment by gioscarda** [comment]
@giohappy 
It seems to be a 'Save as' action, right? If not I don't know how to reach that dialog.
I discussed with @allyoucanmap the possibility to UPDATE the name of the current map without creating a new map.
In mapstore it is possible outside the map, in the home page where the maps are listed.
In GeoNode, as far as I know, it can be done only by editing metedata.
I think this is the current GeoNode behaviour, not involved with the integration of mapstore, so I asked you how to manage this issue.

**Comment by giohappy** [comment]
ok, I think this affects MapStore first since it should provide a way to update the map name. This isn't currently available, so it won't neither be for GeoNode.
We can discuss this enhancement on the MapStore repo in case. I close this for the moment.
