### ISSUE TITLE
Integrate ArcGIS ImageLayer layer type in MapStore

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-mapstore-client#52]
It is required to support layers from GeoNodes's ArcGIS remote services. 

OpenLayers 4 already implements it: https://openlayers.org/en/latest/apidoc/ol.source.ImageArcGISRest.html
Leaflet has plugins (also from ESRI) for that. https://esri.github.io/esri-leaflet/api-reference/layers/image-map-layer.html

**Comment by kappu72** [comment]
closed by https://github.com/geosolutions-it/MapStore2/pull/3296
