### ISSUE TITLE
Customizable XYZ backgrounds

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode-mapstore-client#65]
From MS2 Adapter configuration a user should be able to add custom XYZ backgrounds to MapStore client

**Comment by gioscarda** [comment]
@afabiani is this one still open?

Notice that we are developing the possibility to configure backgrounds from mapstore directly, hence we might just leave this one aside.

**Comment by afabiani** [comment]
Moved to https://github.com/GeoNode/geonode-mapstore-client/issues/12
