### ISSUE TITLE
Management of temporarily styles (Style Editor)

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode-mapstore-client#88]
In the first implementation Style Editor manages  temporarily styles saving them to geoserver.
It should be better to move this logic on MapStore backend and use STYLE_URL/STYLE_FORMAT as parameters in WMS getMap

needed https://github.com/geosolutions-it/geonode-mapstore-client/issues/87
releted to https://github.com/geosolutions-it/MapStore2/issues/3224

**Comment by giohappy** [comment]
in favour of https://github.com/geosolutions-it/MapStore2/issues/3227
