### ISSUE TITLE
Implement new widgets (Style Editor)

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode-mapstore-client#89]
Style Editor has basic widgets as color picker and symbol selector.
It could be interesting to add widgets that helps to write values.

widgets:
- functions
  - categorize
  - recode
  - interpolation
- symbols
  - wkt draw editor

releted to https://github.com/geosolutions-it/MapStore2/issues/3224

**Comment by giohappy** [comment]
closed in favour of https://github.com/geosolutions-it/MapStore2/issues/3228
