### ISSUE TITLE
Add helpers on autocomplete (Style Editor)

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode-mapstore-client#90]
In the first implementation Style Editor will support a basic list of value in the textarea autocomplete.
Could be useful to add helpers to the autocomplete list as link or description.
This issue needs a previous investigation to verify the extendibility of Codemirror hint addon.

releted to https://github.com/geosolutions-it/MapStore2/issues/3224

**Comment by aaime** [comment]
Note that in GeoServer we customized CodeMirror to provide auto-completion, see:
https://github.com/geoserver/geoserver/blob/master/src/web/core/src/main/java/org/geoserver/web/wicket/js/codemirror/js/css.js

**Comment by giohappy** [comment]
closed in favour of https://github.com/geosolutions-it/MapStore2/issues/3229
