### ISSUE TITLE
Style data (Style Editor)

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode-mapstore-client#94]
Currently to get all data needed in the Style Editor we have to make two different request WMS getCapabilities and rest API.

information needed:
- format (rest)
- version (rest)
- name (rest, getCapabilities)
- title (getCapabilities)
- _abstract (getCapabilities)

Is it possible to retrieve all style data only in a single endpoint?

releted to https://github.com/geosolutions-it/MapStore2/issues/3224

**Comment by aaime** [comment]
There is currently no way as the information needed is split among two files, the actual XML config file (handled by the REST API) and the style file itself (title and abstract in getcapabilities are obtained by parsing the SLD and getting those info out of the parsed objects).

To get those informations we'd likely have to create a new type of object, wrapping or subclassing StyleInfo, that also contains the tiltle/abstract obtained from parsing.

**Comment by giohappy** [comment]
closed in favour of https://github.com/geosolutions-it/MapStore2/issues/3232
